### PR TITLE
Rework Welcome page

### LINKED ISSUE #243: Rework Welcome page
As a developer, I want a good-looking welcome page so that the page makes a good first impression.

**Acceptance criteria:**

- In this issue we only focus on the content before "What is devonfw" block. This content should be changed as shown in the mockup (https://projects.invisionapp.com/share/AD11YT9UV93X#/screens), but the navigation and the three buttons should not be changed. The "Browse our solutions" button can be ignored in this issue. 
- The name of the platform must be written as **devonfw** not Devonfw. (Even at the beginning of a sentence)

### PR DESCRIPTION
**Pull request by tobka777**
closes #243

### CODE REVIEW

**Comment by cinnamon-coder-hub** [comment]
I think that there was a mistake in the mockup: 
grafik
According to the issue https://github.com/devonfw/devonfw.github.io/pull/261
the Platformname should always be written as devonfw instead of Devonfw.

**Comment by SchettlerKoehler** [comment]
> I think that there was a mistake in the mockup: grafik According to the issue #261 the Platformname should always be written as devonfw instead of Devonfw.

This is correct. @tobka777 please change this.

**Comment by cinnamon-coder-hub** [comment]
**Comments regarding welcome.css**

- line 152: It seems as if the color-property is not needed for the selector ".welcome-desc2 p strong", because no strong tag is used there or else no text is colored blue

- A design matter in connection with line 165: When the user views the welcome page with under 577 Pixels in wideness the platform name on the left side of the pages top disappears, but there may still be enough space for the platform name in some cases.

MicrosoftTeams-image
 
MicrosoftTeams-image (1)



Finally I wanted to add that I really like the new appearance of the welcome-page!

**Comment by tobka777** [comment]
> > I think that there was a mistake in the mockup: grafik According to the issue #261 the Platformname should always be written as devonfw instead of Devonfw.
> 
> This is correct. @tobka777 please change this.

Ok I changed this and also the copy & paste css in line 152. The responsive issue with the devon logo I didnt worked on that maybe we can resolve this when we work on the redesign of the menu.

**Comment by tobka777** [comment]
@cinnamon-coder-hub can you take a look on my changes. I had some issues to integrate the other features for the startpage from #242 that it looks great.

**Review by cinnamon-coder-hub — CHANGES_REQUESTED** [review]
In line 77: There might be a typo regarding "vendor lockin", from my research I only found it written as "vendor lock-in"

**Review by cinnamon-coder-hub — APPROVED** [review]

**Comment by tobka777** [comment]
Ok I fixed the typo. So it's ready for merge!

**Pull request merged**
